### ISSUE TITLE
Explore methods for web crawling, such as scrapy

### ISSUE THREAD

**Issue by jakobtorben** [jakobtorben/Intelligent-public-web-data-extraction#2]
Acceptance criteria:
- Deciding on the package/method for web crawling that we will use

**Comment by ricardomokhtari** [comment]
Hey guys,

I've done some reading on scrapy vs beautifulsoup. It seems that the main difference between the two is that scrapy is used for _crawling_ while beautifulsoup is used for _scraping_. Meaning that beautifulsoup is mainly just used to return specific elements from pages, whereas scrapy creates a copy of the page and has methods that make it easier to navigate/post process and parse returned information - more useful for our case I think.

It also seems that scrapy runs a lot faster than beautifulsoup (~20X) and also has less overhead (beautifulsoup depends on urlib2/Requests). If we are crawling many pages from >100 companies I think that scrapy has a big advantage here.

I think that scrapy is generally recommended for larger and more complex projects because of its extensibility, whereas beautifulsoup is more applicable for smaller projects due to more overhead and gentle learning curve.

For these reasons, it looks that scrapy is a more applicable tool - what do you guys think?

Refs:
[Scrapy vs BeautifulSoup](https://hexfox.com/p/scrapy-vs-beautifulsoup/)
[Scrapy vs BeautifulSoup vs Selenium](https://medium.com/analytics-vidhya/scrapy-vs-selenium-vs-beautiful-soup-for-web-scraping-24008b6c87b8)

Earlier in the week I also began familiarising myself with scrapy and I have been following this tutorial, if you guys are interested: [Tutorial](https://docs.scrapy.org/en/latest/intro/tutorial.html)

**Comment by jakobtorben** [comment]
Thanks for sharing these resources. I have had a look at them and I agree with what you are saying. Scrappy looks to be more suited for larger projects such as ours since we will be dealing with large volumes of websites. So I think we should try to use Scrapy to get our first approach up and running.
